name: cle_jax
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base
  - mdanalysis
  - numpy=1
  - pandas
  - pytest
  - pip
  - psi4=1.9.1
  - python=3.11
  - scipy
  - setuptools
  - jax=0.5.0
  - jaxlib=0.5.0
  - optax
  - jaxopt
  - networkx
